openapi: 3.0.0
info:
  title: Card Recognition API
  version: 1.0.0
paths:
  /cardinthemiddle:
    get:
      summary: The Card in the middle
      responses:
        '200':
          description: success
  /cardinmyhand/{playerid}:
    get:
      summary: cards in the hand of the player
      parameters:
        - in: path
          name: playerid
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: success
        '404':
          description: card not found